### ISSUE TITLE
Nav Bar and Logo

### ISSUE THREAD

**Issue by Tereseus** [jcochran206/ColmarAcademy#1]
As you can see in the image below there are a few issues with your navigation bar.

1. The logo is missing in the HTML and on the tab
2. The links "On Campus", "Online" etc. should be aligned to the right.

![image](https://user-images.githubusercontent.com/19315896/42137312-5eb9db62-7d38-11e8-946a-e2640d1cc9a2.png)

**Comment by jcochran206** [comment]
updated logo and navbar alignment
