### ISSUE TITLE
Summary - Incomplete

### ISSUE THREAD

**Issue by Tereseus** [jcochran206/ColmarAcademy#5]
There are a few issues which are preventing this project from being complete. You have done a lot of things correctly but these minor issues like the logo and alignment of the nav bar and body are holding your project back. These are not big issues though and should take you no longer than 10 minutes to fix. if you need help feel free to reach out to the advisors. Good job on a lot of things, just a little more to be complete.

**Comment by jcochran206** [comment]
made changes that you suggested
